name: Deploy

on:
  workflow_run:
    workflows: ['Tests']
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: Apply database migrations
        run: pnpx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Install Railway CLI
        run: npm add --global @railway/cli
      - name: Deploy to Railway
        run: RAILWAY_TOKEN=2d73a7db-a90e-4eaf-b5c5-d3e8a2554d79 railway up --service=nestjs-starter
